version: "3.8"

# Run via: mkdir -p database && docker compose up
# Then visit http://localhost/.

services:
  proxy:
    image: nginx:1.19-alpine
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
  backend:
    image: backend
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DATABASE: postgres
    build:
      dockerfile: backDockerfile
    container_name: backend
  redis:
    image: redis
    container_name: redis
  db:
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    container_name: postgres
  frontend:
    image: frontend
    build:
      dockerfile: frontDockerfile
    container_name: frontend
