version: "3.8"

services:
  backend:
    image: backend
    build:
      dockerfile: backDockerfile
    ports:
      - 8000:8000
    container_name: backend
  frontend:
    image: frontend
    build:
      dockerfile: frontDockerfile
    ports:
      - 5001:5000
    container_name: frontend
